# =============================================================================
# FATORI-V • Fault Injection Framework
# File: fi/settings.py
# -----------------------------------------------------------------------------
# Central defaults:
#   • Serial device/baud, SEM clock
#   • Session naming
#   • Log directory and write policy
#   • Logging category toggles (per class)
#   • Injection-rate model (platform cap parameters)
#   • ACME extraction defaults (EBD path, board, cache)
# =============================================================================

from __future__ import annotations

# ---------- serial / SEM defaults --------------------------------------------
DEFAULT_SEM_DEVICE     = "/dev/ttyUSB1"
BAUDRATE               = 1_250_000
SEM_FREQ_HZ            = 100_000_000

# ---------- session naming defaults ------------------------------------------
DEFAULT_RUN_NAME       = "sem_m0"
DEFAULT_SESSION_LABEL  = "session"

# ---------- logging layout ----------------------------------------------------
LOG_DIR                = "results"
DEFER_LOG_WRITE        = True     # file is kept open; header is emitted once

# ---------- logging category toggles (per class) ------------------------------
# Each class can be enabled/disabled globally here. The event logger consults
# these switches to decide which messages are written to the log file. The log
# header lists only the categories enabled below.
#
# Classes:
#   • SEM CMD   : Raw SEM monitor UART traffic ([SEND]*/[RECV])
#   • CNSL CMD  : Console commands typed by the user
#   • CNSL MODE : Console mode transitions [MAN]↔[DRI]
#   • PROF TIME : Time profile lifecycle (start/pause/resume/finish)
#   • PROF AREA : Area profile lifecycle (start/finish)
#   • INFO      : Informational events
#   • ERROR     : Error lines
LOG_SEM_CMD_ENABLED    = True
LOG_CNSL_CMD_ENABLED   = True
LOG_CNSL_MODE_ENABLED  = True
LOG_PROF_TIME_ENABLED  = True
LOG_PROF_AREA_ENABLED  = True
LOG_INFO_ENABLED       = True
LOG_ERR_ENABLED        = True

# ---------- Injection-rate model (platform-dependent) ------------------------
# Parameters for computing a safe, platform-dependent maximum injection rate.
# The controller reconciles requested cadence (rate/period) against this cap
# before creating any time profile. The model scales an at-Fmax latency to
# the actual SEM clock and applies a safety derate; an optional UART ceiling
# can be applied to reflect host-side throughput limits.
SEM_ICAP_FMAX_HZ: int = 200_000_000          # ICAP/SEM controller maximum clock (Hz)
SEM_INJECT_LATENCY_US_AT_FMAX: float = 50.0  # Best-case per-injection latency at ICAP Fmax (µs)
INJECTION_RATE_SAFETY_DERATE: float = 1.0    # Safety derate [0..1]
INJECTION_RATE_UART_CAP_HZ: float = 0.0      # Optional absolute controller-side cap (Hz). 0 disables.

# ---------- ACME extraction defaults -----------------------------------------
# Default path to the Essential Bits Data file. Provide an absolute or relative
# path to the .ebd generated by Vivado (bitstream property: SEU.ESSENTIALBITS).
EBD_DEFAULT_PATH       = "build/design.ebd"

# Default device/board selection used by the ACME extractor when callers do not
# explicitly pass a 'board' argument (e.g., area=device). Valid examples:
#   "xcku040" | "ku105" | "kcu105" (UltraScale XCKU040)
#   "basys3"  | "xc7a35t" (Artix-7 Basys3)
ACME_DEFAULT_BOARD     = "xcku040"

# Directory where ACME-derived address lists are cached. The filename encodes
# the board, EBD filesize/mtime and a short hash of the path to avoid clashes.
# This keeps repeated runs fast and deterministic.
ACME_CACHE_DIR         = f"{LOG_DIR}/.acme_cache"

# -----------------------------------------------------------------------------
# End of file
# -----------------------------------------------------------------------------
