#ifndef H_IOB_SOC_AXI_FULL_XBAR_CONF_H
#define H_IOB_SOC_AXI_FULL_XBAR_CONF_H

#define IOB_SOC_AXI_FULL_XBAR_ID_W 0
#define IOB_SOC_AXI_FULL_XBAR_LEN_W 0
#define IOB_SOC_AXI_FULL_XBAR_VERSION 0x0081

#endif // H_IOB_SOC_AXI_FULL_XBAR_CONF_H
