// =============================================================
// Auto-generated by tmr_select.py
// Source JSON   : fault_tolerance/tmr/wrapped_registers.json
// Folder        : /home/jaguiar/sandbox/Fatori-V/iob_soc_V1.0/hardware/src
// Percentage    : 0%
// Seed          : 399788
// Generated on  : 22/11/2025 16:58
// =============================================================
// made by: Jaime Aguiar - IST Master's Student
// =============================================================

// =============================================================
// TMR Register Defines:
//
// Each register in the fatori-v design can be selectively
// triplicated for Triple Modular Redundancy (TMR) protection.
// The <reg>_TMR_EN macros indicate whether TMR is enabled (1)
// or disabled (0) for that specific register. These defines
// allow the RTL code to conditionally instantiate triplicated
// logic only for the registers that require redundancy.
// These condition can be configured by the user.
// =============================================================



// =============================================================
// MACRO's Definitions:
// * Reg List after
// -------------------------------------------------------------

`ifndef FATORI_TMR_CONFIG_SVH
`define FATORI_TMR_CONFIG_SVH

// From ibex_controller.sv
`define mem_resp_intg_err_irq_pending_q_TMR_EN 0
`define mem_resp_intg_err_addr_q_TMR_EN 0
`define debug_cause_q_TMR_EN 0
`define ctrl_fsm_cs_TMR_EN 0
`define nmi_mode_q_TMR_EN 0
`define do_single_step_q_TMR_EN 0
`define debug_mode_q_TMR_EN 0
`define enter_debug_mode_prio_q_TMR_EN 0
`define load_err_q_TMR_EN 0
`define store_err_q_TMR_EN 0
`define exc_req_q_TMR_EN 0
`define illegal_insn_q_TMR_EN 0

// From ibex_core.sv
`define last_fetch_enable_TMR_EN 0
`define pc_at_fetch_disable_TMR_EN 0

// From ibex_cs_registers.sv
`define priv_lvl_q_TMR_EN 0
`define mcountinhibit_TMR_EN 0

// From ibex_csr.sv
`define rdata_TMR_EN 0
`define shadow_TMR_EN 0

// From ibex_decoder.sv
`define use_rs3_TMR_EN 0

// From ibex_dummy_instr.sv
`define dummy_instr_seed_TMR_EN 0
`define dummy_cnt_TMR_EN 0

// From ibex_fetch_fifo.sv
`define instr_addr_TMR_EN 0
`define instr_addr_no_rst_TMR_EN 0
`define valid_TMR_EN 0
`define rdata_0_TMR_EN 0
`define rdata_1_TMR_EN 0
`define rdata_2_TMR_EN 0
`define err_0_TMR_EN 0
`define err_1_TMR_EN 0
`define err_2_TMR_EN 0

// From ibex_id_stage.sv
`define imd_val_q_reg_0_TMR_EN 0
`define imd_val_q_reg_1_TMR_EN 0
`define branch_set_raw_TMR_EN 0
`define branch_jump_set_done_TMR_EN 0
`define branch_taken_TMR_EN 0
`define id_fsm_q_TMR_EN 0

// From ibex_top.sv
`define core_busy_TMR_EN 0
`define scramble_key_TMR_EN 0
`define scramble_nonce_TMR_EN 0
`define scramble_key_valid_TMR_EN 0
`define scramble_req_TMR_EN 0
`define sampled_scramble_key_TMR_EN 0
`define pending_dside_accesses_0_TMR_EN 0
`define pending_dside_accesses_1_TMR_EN 0

// From ibex_if_stage.sv
`define dummy_instr_id_TMR_EN 0
`define instr_valid_id_q_reg_TMR_EN 0
`define instr_new_id_q_reg_TMR_EN 0
`define instr_rdata_id_TMR_EN 0
`define instr_rdata_alu_id_TMR_EN 0
`define instr_fetch_err_TMR_EN 0
`define instr_fetch_err_plus2_TMR_EN 0
`define instr_rdata_c_id_TMR_EN 0
`define instr_is_compressed_id_TMR_EN 0
`define illegal_c_insn_id_TMR_EN 0
`define pc_id_TMR_EN 0
`define instr_rdata_id_no_rst_TMR_EN 0
`define instr_rdata_alu_id_no_rst_TMR_EN 0
`define instr_fetch_err_no_rst_TMR_EN 0
`define instr_fetch_err_plus2_no_rst_TMR_EN 0
`define instr_rdata_c_id_no_rst_TMR_EN 0
`define instr_is_compressed_id_no_rst_TMR_EN 0
`define illegal_c_insn_id_no_rst_TMR_EN 0
`define pc_id_no_rst_TMR_EN 0
`define prev_instr_seq_TMR_EN 0
`define instr_bp_taken_TMR_EN 0
`define instr_bp_taken_no_rst_TMR_EN 0
`define instr_skid_valid_q_TMR_EN 0
`define instr_skid_bp_taken_q_TMR_EN 0
`define instr_skid_data_q_TMR_EN 0
`define instr_skid_addr_q_TMR_EN 0
`define instr_skid_bp_taken_q_no_rst_TMR_EN 0
`define instr_skid_data_q_no_rst_TMR_EN 0
`define instr_skid_addr_q_no_rst_TMR_EN 0

// From ibex_load_store_unit.sv
`define rdata_TMR_EN 0
`define rdata_offset_TMR_EN 0
`define data_type_TMR_EN 0
`define data_sign_ext_TMR_EN 0
`define data_we_TMR_EN 0
`define addr_last_TMR_EN 0
`define ls_fsm_cs_TMR_EN 0
`define handle_misaligned_TMR_EN 0
`define pmp_err_TMR_EN 0
`define lsu_err_TMR_EN 0
`define fcov_mis_2_en_TMR_EN 0
`define fcov_mis_bus_err_1_TMR_EN 0

// From ibex_lockstep.sv
`define shadow_inputs_0_TMR_EN 0
`define shadow_inputs_1_TMR_EN 0
`define shadow_tag_rdata_0_TMR_EN 0
`define shadow_tag_rdata_1_TMR_EN 0
`define shadow_data_rdata_0_TMR_EN 0
`define shadow_data_rdata_1_TMR_EN 0

// From ibex_prefetch_buffer.sv
`define stored_addr_TMR_EN 0
`define fetch_addr_TMR_EN 0
`define valid_req_TMR_EN 0
`define discard_req_TMR_EN 0
`define rdata_outstanding_TMR_EN 0
`define branch_discard_TMR_EN 0

// From ibex_wb_stage.sv
`define wb_valid_TMR_EN 0
`define rf_we_wb_TMR_EN 0
`define rf_waddr_wb_TMR_EN 0
`define rf_wdata_wb_TMR_EN 0
`define wb_instr_type_TMR_EN 0
`define wb_pc_TMR_EN 0
`define wb_compressed_TMR_EN 0
`define wb_count_TMR_EN 0
`define dummy_instr_wb_TMR_EN 0

// From ibex_fault_mgr.sv
`define minor_cnt_o_TMR_EN 0
`define major_cnt_o_TMR_EN 0
`define minor_seen_o_TMR_EN 0
`define fault_sticky_o_TMR_EN 0
`define fetch_en_q_TMR_EN 0
`define state_q_TMR_EN 0



// =============================================================
// Register List:

// -------------------------------------------------------------
// Enabled Registers:
// -------------------------------------------------------------

// -------------------------------------------------------------
// Disabled Registers:
// -------------------------------------------------------------

// ibex_controller.sv:
//   ctrl_fsm_cs
//   debug_cause_q
//   debug_mode_q
//   do_single_step_q
//   enter_debug_mode_prio_q
//   exc_req_q
//   illegal_insn_q
//   load_err_q
//   mem_resp_intg_err_addr_q
//   mem_resp_intg_err_irq_pending_q
//   nmi_mode_q
//   store_err_q

// ibex_core.sv:
//   last_fetch_enable
//   pc_at_fetch_disable

// ibex_cs_registers.sv:
//   mcountinhibit
//   priv_lvl_q

// ibex_csr.sv:
//   rdata
//   shadow

// ibex_decoder.sv:
//   use_rs3

// ibex_dummy_instr.sv:
//   dummy_cnt
//   dummy_instr_seed

// ibex_fetch_fifo.sv:
//   err_0
//   err_1
//   err_2
//   instr_addr
//   instr_addr_no_rst
//   rdata_0
//   rdata_1
//   rdata_2
//   valid

// ibex_id_stage.sv:
//   branch_jump_set_done
//   branch_set_raw
//   branch_taken
//   id_fsm_q
//   imd_val_q_reg_0
//   imd_val_q_reg_1

// ibex_top.sv:
//   core_busy
//   pending_dside_accesses_0
//   pending_dside_accesses_1
//   sampled_scramble_key
//   scramble_key
//   scramble_key_valid
//   scramble_nonce
//   scramble_req

// ibex_if_stage.sv:
//   dummy_instr_id
//   illegal_c_insn_id
//   illegal_c_insn_id_no_rst
//   instr_bp_taken
//   instr_bp_taken_no_rst
//   instr_fetch_err
//   instr_fetch_err_no_rst
//   instr_fetch_err_plus2
//   instr_fetch_err_plus2_no_rst
//   instr_is_compressed_id
//   instr_is_compressed_id_no_rst
//   instr_new_id_q_reg
//   instr_rdata_alu_id
//   instr_rdata_alu_id_no_rst
//   instr_rdata_c_id
//   instr_rdata_c_id_no_rst
//   instr_rdata_id
//   instr_rdata_id_no_rst
//   instr_skid_addr_q
//   instr_skid_addr_q_no_rst
//   instr_skid_bp_taken_q
//   instr_skid_bp_taken_q_no_rst
//   instr_skid_data_q
//   instr_skid_data_q_no_rst
//   instr_skid_valid_q
//   instr_valid_id_q_reg
//   pc_id
//   pc_id_no_rst
//   prev_instr_seq

// ibex_load_store_unit.sv:
//   addr_last
//   data_sign_ext
//   data_type
//   data_we
//   fcov_mis_2_en
//   fcov_mis_bus_err_1
//   handle_misaligned
//   ls_fsm_cs
//   lsu_err
//   pmp_err
//   rdata
//   rdata_offset

// ibex_lockstep.sv:
//   shadow_data_rdata_0
//   shadow_data_rdata_1
//   shadow_inputs_0
//   shadow_inputs_1
//   shadow_tag_rdata_0
//   shadow_tag_rdata_1

// ibex_prefetch_buffer.sv:
//   branch_discard
//   discard_req
//   fetch_addr
//   rdata_outstanding
//   stored_addr
//   valid_req

// ibex_wb_stage.sv:
//   dummy_instr_wb
//   rf_waddr_wb
//   rf_wdata_wb
//   rf_we_wb
//   wb_compressed
//   wb_count
//   wb_instr_type
//   wb_pc
//   wb_valid

// ibex_fault_mgr.sv:
//   fault_sticky_o
//   fetch_en_q
//   major_cnt_o
//   minor_cnt_o
//   minor_seen_o
//   state_q


`endif
